version: '2'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - /var/tmp/redis:/data
  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"

